### PR TITLE
Do not accept this push as this is a BfA update and not for Legion.

### PR DESCRIPTION
**Pull request by Thrumbar**
This is to let you know what I have done so far until there is a BfA branch for quest..

https://github.com/Thrumbar/Carbonite.Quests

### CODE REVIEW

**Comment by Thrumbar** [comment]
Map ID's need updating and when I tried to deselect loading the quest database it produced this error and quest no longer loads....

Message: Interface\AddOns\Carbonite.Quests\NxQuest.lua:3143: Division by zero
Time: Tue Jun 26 17:20:10 2018
Count: 1
Stack: Interface\AddOns\Carbonite.Quests\NxQuest.lua:3143: Division by zero
Interface\AddOns\Carbonite.Quests\NxQuest.lua:3143: in function `?'
Interface\AddOns\Carbonite.Quests\NxQuest.lua:2735: in function `Init'
Interface\AddOns\Carbonite.Quests\NxQuest.lua:2135: in function `func'
...\AddOns\Carbonite\Libs\AceTimer-3.0\AceTimer-3.0.lua:57: in function <...\AddOns\Carbonite\Libs\AceTimer-3.0\AceTimer-3.0.lua:50>

Locals: self = <table> {
 IconTracking = <table> {
 }
 UnpackCategory = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:10272
 DailyTypes = <table> {
 }
 IsTargeted = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:10038
 Menu_OnTrack = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:3227
 GetQuestReward = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:3280
 DecodeComRcv = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:10908
 MsgNotInDB = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:5194
 Watch = <table> {
 }
 PartyStartSend = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:11145
 GOpts = <table> {
 }
 NullQuest = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:11289
 CheckQuestSE = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:3165
 GetFromPlyr = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:5008
 Custom = <table> {
 }
 OldMap = 0
 IdToCurQ = <table> {
 }
 PerColors = <table> {
 }
 GetClosestObjectivePos = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:10552
 RecordQuestsLog = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:3466
 ExtractTitle = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:4243
 CalcCNumMax = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:4063
 ScanBlizzQuestDataZone = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:3991
 FindCur = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:4732
 TooltipProcess = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:5279
 FindNewQuest = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:4342
 UnpackNext = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:10263
 ShowUIPanel = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:5806
 CapturePlyrData = <table> {
 }
 GetObjectiveType = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:10323
 PartyUpdateTimer = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:11138
 MapChanged = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:3969
 OnParty_members_changed = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:11004
 AlchemistsApprenticeData = <table> {
 }
 UpdateQuestDetails = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:8139
 DailyIds = <table> {
 }
 CalcDesc = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:4204
 QLocColors = <table> {
 }
 CalcPreviousDone = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:4106
 AccessAllQuests = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:3414
 IconOnMouseDown = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:8084
 UpdateGiverIconMenu = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:9933
 WatchAtLogin = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:4839
 CreateLink = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:4235
 LightHeadedAttach = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:5874
 RecordQuestAcceptOrFinish = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:4391
 ExpandQuests = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:3344
 Init

**Comment by Thrumbar** [comment]
Will get this until zones are changed to new numbers....

Message: ...lizzard_MapCanvas\MapCanvas_ScrollContainerMixin.lua:425: attempt to index local 'layers' (a nil value)
Time: Wed Jun 27 15:39:24 2018
Count: 1
Stack: ...lizzard_MapCanvas\MapCanvas_ScrollContainerMixin.lua:425: attempt to index local 'layers' (a nil value)
...lizzard_MapCanvas\MapCanvas_ScrollContainerMixin.lua:425: in function `CreateZoomLevels'
...lizzard_MapCanvas\MapCanvas_ScrollContainerMixin.lua:412: in function `OnCanvasSizeChanged'
...lizzard_MapCanvas\MapCanvas_ScrollContainerMixin.lua:404: in function `SetMapID'
...ace\AddOns\Blizzard_MapCanvas\Blizzard_MapCanvas.lua:31: in function `SetMapID'
Interface\AddOns\Carbonite.Quests\NxQuest.lua:3949: in function `ScanBlizzQuestDataTimer'
Interface\AddOns\Carbonite.Quests\NxQuest.lua:3913: in function <Interface\AddOns\Carbonite.Quests\NxQuest.lua:3913>

Locals: self = <unnamed> {
 0 = <userdata>
 MarkCanvasDirty = <function> defined @Interface\AddOns\Blizzard_MapCanvas\MapCanvas_ScrollContainerMixin.lua:381
 GetMinZoomViewRect = <function> defined @Interface\AddOns\Blizzard_MapCanvas\MapCanvas_ScrollContainerMixin.lua:544
 GetNormalizedHorizontalScroll = <function> defined @Interface\AddOns\Blizzard_MapCanvas\MapCanvas_ScrollContainerMixin.lua:700
 SetPanTarget = <function> defined @Interface\AddOns\Blizzard_MapCanvas\MapCanvas_ScrollContainerMixin.lua:577
 DenormalizeVerticalSize = <function> defined @Interface\AddOns\Blizzard_MapCanvas\MapCanvas_ScrollContainerMixin.lua:725
 IsAtMaxZoom = <function> defined @Interface\AddOns\Blizzard_MapCanvas\MapCanvas_ScrollContainerMixin.lua:644
 AccumulateMouseDeltas = <function> defined @Interface\AddOns\Blizzard_MapCanvas\MapCanvas_ScrollContainerMixin.lua:245
 ScalingMode = <function> defined @Interface\AddOns\Blizzard_MapCanvas\MapCanvas_ScrollContainerMixin.lua:290
 GetMap = <function> defined @Interface\AddOns\Blizzard_MapCanvas\MapCanvas_ScrollContainerMixin.lua:656
 IsZoomingIn = <function> defined @Interface\AddOns\Blizzard_MapCanvas\MapCanvas_ScrollContainerMixin.lua:636
 ZoomOut = <function> defined @Interface\AddOns\Blizzard_MapCanvas\MapCanvas_ScrollContainerMixin.lua:598
 ShouldZoomInstantly = <function> defined @Interface\AddOns\Blizzard_MapCanvas\MapCanvas_ScrollContainerMixin.lua:536
 SetScalingMode = <function> defined @Interface\AddOns\Blizzard_MapCanvas\MapCanvas_ScrollContainerMixin.lua:286
 targetScale = 1.6931137724551
 GetNormalizedCursorPosition = <function> defined @Interface\AddOns\Blizzard_MapCanvas\MapCanvas_ScrollContainerMixin.lua:750
 TryPanOrZoomOnClick = <function> defined @Interface\AddOns\Blizzard_MapCanvas\MapCanvas_ScrollContainerMixin.lua:86
 shouldPanOnClick = false
 SetZoomTarget = <function> defined @Interface\AddOns\Blizzard_MapCanvas\MapCanvas_ScrollContainerMixin.lua:582
 normalizedPanXLerpAmount = 0.15
 NormalizeUIPosition = <function> defined @Interface\AddOns\Blizzard_MapCanvas\MapCanvas_ScrollContainerMixin.lua:745
 OnMouseUp = <function> defined @Interface\AddOns\Blizzard_MapCanvas\MapCanvas_ScrollContainerMixin.lua:104
 MarkAreaTriggersDirty = <function> defined @Interface\AddOns\Blizzard_MapCanvas\MapCanvas_ScrollContainerMixin.lua:373
 CalculateViewRect = <function> defined @Interface\AddOns\Blizzard_MapCanvas\MapCanvas_ScrollContainerMixin.lua:548
 ResetZoom = <function> defined @Interface\AddOns\Blizzard_MapCanvas\MapCanvas_ScrollContainerMixin.lua:610
 NormalizeHorizontalSize = <function> defined @Interface\AddOns\Blizzard_MapCanvas\MapCanvas_ScrollContainerMixin.lua:713
 SetNormalizedHorizontalScroll = <function> defined @Interface\AddOns\Blizzard_MapCanvas\MapCanvas_ScrollContainerMixin.lua:695
 OnLoad = <function> defined @Interface\AddOns\Blizzard_MapCanvas\MapCanvas_ScrollContainerMixin.lua:7
 Child = <unnamed> {
 }
 zoomLevels = <table> {
 }
 SetShouldPanOnClick = <function> defined @Interface\AddOns\Blizzard_MapCanvas\MapCanvas_ScrollContainerMixin.lua:524
 scrollYExtentsMin = 0.5
 areaTriggersDirty = true
 scrollXExtentsMin = 0.5004419897047
 SetCanvasSize =

**Comment by Thrumbar** [comment]
Message: Interface\AddOns\Carbonite.Quests\NxQuest.lua:10401: attempt to perform arithmetic on a nil value
Time: Wed Jun 27 15:39:26 2018
Count: 1
Stack: Interface\AddOns\Carbonite.Quests\NxQuest.lua:10401: attempt to perform arithmetic on a nil value
Interface\AddOns\Carbonite.Quests\NxQuest.lua:10401: in function `GetPosLoc'
Interface\AddOns\Carbonite.Quests\NxQuest.lua:10343: in function `GetSEPos'
Interface\AddOns\Carbonite.Quests\NxQuest.lua:3011: in function `ProcessQuestDB'
Interface\AddOns\Carbonite.Quests\NxQuest.lua:3148: in function <Interface\AddOns\Carbonite.Quests\NxQuest.lua:3148>

Locals: self = <table> {
 IconTracking = <table> {
 }
 UnpackCategory = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:10272
 DailyTypes = <table> {
 }
 IsTargeted = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:10038
 Menu_OnTrack = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:3227
 GetQuestReward = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:3280
 DecodeComRcv = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:10908
 MsgNotInDB = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:5194
 Watch = <table> {
 }
 PartyStartSend = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:11145
 SortQuests = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:4267
 NullQuest = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:11289
 CheckQuestSE = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:3165
 GetFromPlyr = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:5008
 Custom = <table> {
 }
 TTChange = <table> {
 }
 TooltipProcess2 = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:5303
 IdToCurQ = <table> {
 }
 PerColors = <table> {
 }
 GetClosestObjectivePos = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:10552
 RecordQuestsLog = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:3466
 ExtractTitle = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:4243
 CalcCNumMax = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:4063
 UnpackObjective = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:10310
 ClearCaptured = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:5028
 TooltipProcess = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:5279
 SelectBlizz = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:3334
 UnpackNext = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:10263
 ShowUIPanel = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:5806
 CapturePlyrData = <table> {
 }
 GetObjectiveType = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:10323
 PartyUpdateTimer = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:11138
 MapChanged = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:3969
 OnParty_members_changed = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:11004
 AlchemistsApprenticeData = <table> {
 }
 UpdateQuestDetails = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:8139
 DailyIds = <table> {
 }
 CalcDesc = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:4204
 QLocColors = <table> {
 }
 CalcPreviousDone = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:4106
 AccessAllQuests = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:3414
 IconOnMouseDown = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:8084
 UpdateGiverIconMenu = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:9933
 WatchAtLogin = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:4839
 CreateLink = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:4235
 LightHeadedAttach = <function> defined @Interface\Ad

**Comment by IrcDirk** [comment]
I need to scrap whole quests database again with right UIMapIDs.

**Pull request closed without merging**
